# frozen_string_literal: true
# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.define :test_vm do |test_vm|
    # Box name
    test_vm.vm.box = "voidbox"
    test_vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
    test_vm.vm.network :private_network, :ip => '10.20.30.40'
    test_vm.vm.network :public_network, :ip => '10.20.30.41'
  end

  # Options for Libvirt Vagrant provider.
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"

    # The name of the server, where Libvirtd is running.
    # libvirt.host = "localhost"

    # If use ssh tunnel to connect to Libvirt.
    libvirt.connect_via_ssh = false

    # The username and password to access Libvirt. Password is not used when
    # connecting via ssh.
    libvirt.username = "root"
    #libvirt.password = "secret"

    # Libvirt storage pool name, where box image and instance snapshots will
    # be stored.
    libvirt.storage_pool_name = "default"

    # Set a prefix for the machines that's different than the project dir name.
    #libvirt.default_prefix = ''
  end
end

# vim: set filetype=ruby
